[build]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"

[context.branch-deploy]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"

[context.deploy-preview]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"
